# Generated by Django 5.0.7 on 2024-10-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('produto', models.CharField(max_length=240)),
                ('grupo', models.CharField(max_length=240)),
                ('detalhe', models.TextField(max_length=700)),
                ('codigo', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('estoque', models.IntegerField(max_length=1000)),
                ('custo', models.BooleanField()),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
