# Generated by Django 5.0.7 on 2024-10-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='banco',
            name='estoque',
            field=models.IntegerField(),
        ),
    ]
