# Generated by Django 5.0.7 on 2024-10-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_rename_banco_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='custo',
            field=models.FloatField(),
        ),
    ]
