# Generated by Django 5.0.7 on 2024-10-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_custo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='grupo',
            field=models.ForeignKey(max_length=240, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque.produtogroup'),
        ),
    ]
