# Generated by Django 5.0.7 on 2024-10-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_banco_codigo_alter_banco_estoque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banco',
            new_name='Produto',
        ),
    ]
